use serde::Serialize;

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Recovery {
    pub kind: &'static str,
    pub retryable: bool,
    pub guidance: &'static str,
}

// Match only errors generated by our adapters. Unknown plugin errors get neutral
// guidance; never parse a remote body, echo it, or infer an automatic retry.
pub fn advice(error: &str) -> Recovery {
    let (kind, retryable, guidance) = match error {
        error if error.starts_with("Memory ") || error.starts_with("Saved memory ") => ("memory", false, "Open Memory to review, shorten or disable preferences. Your message was not saved; your draft is restored."),
        error if error.starts_with("Workspace instructions") || error.starts_with("Saved workspace instructions") => ("instructions", false, "Open Instructions to review AGENTS.md again or disable it. Your message was not saved; your draft is restored."),
        error if error.contains("context budget") || error.starts_with("Context window leaves no input room.") || error.starts_with("Model context limit reached.") => ("contextLimit", false, "Review this model’s context window in Model connection, reduce the output token limit, or start a new chat with a shorter message. Already applied tool effects remain."),
        "Response stopped." | "Response stopped. Your message was not saved." => ("stopped", false, "Your draft is restored. Send it when you are ready."),
        "Model request timed out. Adjust the request timeout or try again." => ("timeout", true, "Your message was not saved. Increase the timeout for a slow model, or retry the current draft."),
        "Agent run timed out while working or waiting for approval. Your message was not saved." => ("timeout", true, "Your message was not saved. Increase the timeout or retry the current draft, then review each file request."),
        "Agent reached its tool or model-call limit. Your message was not saved." | "Agent reached its model-call limit." | "Tool context exceeds the 128 KiB limit." => ("outputLimit", false, "The agent run reached its local budget. Narrow the task or disable folder tools before sending again."),
        error if error.starts_with("Tool request failed (HTTP ") || error == "Model did not return a JSON tool response. Disable folder tools or check model support." => ("configuration", false, "Disable folder tools or choose a model that supports Chat Completions function calls."),
        "Could not reach the model. Check the endpoint and whether the server is running." | "Connection interrupted before the response finished." | "Connection ended before the response finished." => ("network", true, "Your message was not saved. Check the connection, then retry the current draft."),
        "Model rate limit reached. Try again later." => ("rateLimit", true, "Wait before retrying the current draft. Dolores will not retry automatically."),
        "Model access denied. Check your API key and permissions." => ("access", false, "Check the API key and permissions in Model connection. Your draft is restored."),
        "Model endpoint not found. Check the base URL and model ID." => ("configuration", false, "Check the endpoint and selected model in Model connection."),
        "Response reached the model output limit. Try a shorter request." => ("outputLimit", true, "Increase the output token limit or shorten your draft, then retry. The incomplete reply was not saved."),
        "Response exceeds the 128 KiB limit." => ("outputLimit", false, "The app’s text limit was reached. Shorten the request or lower the output token limit."),
        "Could not read or save local conversation data." => ("storage", false, "Check local storage before sending again. Review Trajectory to confirm what was saved."),
        error if error.starts_with("Model request failed (HTTP ") => {
            let status = error.strip_prefix("Model request failed (HTTP ").and_then(|v| v.split(')').next()).and_then(|v| v.parse::<u16>().ok());
            if status.is_some_and(|status| status == 408 || (500..=599).contains(&status)) {
                ("provider", true, "The model server could not complete the request. Wait, then retry the current draft.")
            } else {
                ("configuration", false, "Review the selected model and connection settings before sending again.")
            }
        }
        _ => ("unknown", false, "Review the error before sending again. Dolores will not retry automatically."),
    };
    Recovery {
        kind,
        retryable,
        guidance,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn known_failures_have_explicit_manual_recovery_and_unknown_errors_stay_neutral() {
        assert_eq!(
            advice("Model request timed out. Adjust the request timeout or try again.").kind,
            "timeout"
        );
        assert!(
            advice("Model request failed (HTTP 503). Check your connection settings.").retryable
        );
        assert!(
            !advice("Model request failed (HTTP 400). Check your connection settings.").retryable
        );
        assert_eq!(advice("Response stopped.").kind, "stopped");
        let context = advice("Message, instructions and tools exceed the model context budget. Shorten your message, increase the context window, or reduce the output token limit.");
        assert_eq!(context.kind, "contextLimit");
        assert!(!context.retryable);
        assert_eq!(advice("Agent run timed out while working or waiting for approval. Your message was not saved.").kind, "timeout");
        assert!(advice("Agent run timed out while working or waiting for approval. Your message was not saved.").retryable);
        assert!(
            !advice("Agent reached its tool or model-call limit. Your message was not saved.")
                .retryable
        );
        assert_eq!(
            advice("Tool request failed (HTTP 400). Disable folder tools or check model support.")
                .kind,
            "configuration"
        );
        assert!(!advice("Model access denied. Check your API key and permissions.").retryable);
        let unknown = advice("foreign plugin detail");
        assert_eq!(unknown.kind, "unknown");
        assert!(!unknown.guidance.contains("foreign"));
    }
}
