"""Generate platform icons from the original infinity outline (Pillow required)."""
import argparse
import io
from pathlib import Path
import re
import xml.etree.ElementTree as ET
from PIL import Image, ImageDraw

ROOT=Path(__file__).resolve().parents[1]
SVG=ROOT/'assets/dolores.svg'

def outputs():
    root=ET.fromstring(SVG.read_bytes())
    tile=root.find('{*}rect');mark=root.find('{*}path')
    if root.attrib.get('viewBox')!='0 0 256 256' or tile is None or mark is None:
        raise ValueError('Expected the reviewed 256-square tile and cubic infinity path.')
    tokens=re.findall(r'[MCZ]|-?\d+(?:\.\d+)?',mark.attrib['d'])
    if re.sub(r'[MCZ\d.\s-]','',mark.attrib['d']): raise ValueError('Only M/C/Z path commands are supported.')
    if tokens.count('M')!=1 or tokens[-1]!='Z': raise ValueError('Expected one closed infinity outline.')
    points=[];index=0
    while index<len(tokens):
        if tokens[index]=='Z': index+=1;continue
        command=tokens[index];count=2 if command=='M' else 6
        values=list(map(float,tokens[index+1:index+1+count]));index+=count+1
        if len(values)!=count: raise ValueError('Incomplete path command.')
        if command=='M': points.append(tuple(values));continue
        start=points[-1];a=values[:2];b=values[2:4];end=values[4:]
        for step in range(1,65):
            t=step/64;u=1-t
            points.append(tuple(u**3*start[c]+3*u*u*t*a[c]+3*u*t*t*b[c]+t**3*end[c] for c in (0,1)))
    image=Image.new('RGBA',(2048,2048));draw=ImageDraw.Draw(image)
    draw.rounded_rectangle((0,0,2047,2047),radius=float(tile.attrib['rx'])*8,fill=tile.attrib['fill'])
    draw.polygon([(x*8,y*8) for x,y in points],fill=mark.attrib['fill'])
    result={ROOT/'public/dolores.svg':SVG.read_bytes()}
    def encoded(size,kind,**options):
        stream=io.BytesIO();image.resize((size,size),Image.Resampling.LANCZOS).save(stream,format=kind,**options);return stream.getvalue()
    for target in ('assets/dolores.png','src-tauri/icons/icon.png'): result[ROOT/target]=encoded(256,'PNG')
    ico=encoded(1024,'ICO',sizes=[(n,n) for n in (16,24,32,48,64,128,256)])
    for target in ('src-tauri/icons/icon.ico','apps/dolores_flutter/windows/runner/resources/app_icon.ico'): result[ROOT/target]=ico
    result[ROOT/'src-tauri/icons/icon.icns']=encoded(1024,'ICNS')
    for size in (16,32,64,128,256,512,1024):
        result[ROOT/f'apps/dolores_flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_{size}.png']=encoded(size,'PNG')
    png=encoded(64,'PNG')
    header='// Generated by scripts/generate-icons.py from assets/dolores.svg.\n#pragma once\nstatic const unsigned char kDoloresIcon[] = {\n'
    header+='\n'.join('  '+', '.join(f'0x{v:02x}' for v in png[i:i+16])+',' for i in range(0,len(png),16))+'\n};\n'
    result[ROOT/'apps/dolores_flutter/linux/runner/dolores_icon.h']=header.encode()
    return result

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    result=outputs();different=[p for p,v in result.items() if not p.exists() or p.read_bytes()!=v]
    if args.check and different: parser.exit(1,'Regenerate icons: '+', '.join(str(p.relative_to(ROOT)) for p in different)+'\n')
    if not args.check:
        for path,value in result.items(): path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(value)
    print(f'{len(result)} logo outputs '+('match the source.' if args.check else 'generated.'))

if __name__=='__main__': main()
